info:
  build:
    artifact: rich-attachment-service
    name: rich-attachment-service
    description: 附件服务
    version: 1.0.0-RELEASE
attachment:
  cloud:
    aliyun:
      root: rich
      endpoint: oss-cn-shanghai.aliyuncs.com
      access-key-id: ENC(fRJNh0Qn783+b9m32rQQFGdgXDRiDEgahp+Eiy/cVik=)
      access-key-secret: ENC(Wg16nGSWPpo0C+9ot0RLuttvrxn+X+qS35FsUdifGEVItnnmnRHGmQ==)
      bucket: rich-attachment
  local:
    path: D:\\
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
